# Generated by Django 4.2 on 2023-04-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_of_institude', models.CharField(choices=[('c', 'college'), ('h', 'high school')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.ImageField(unique=True, upload_to='')),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male'), ('u', 'undefined')], max_length=1)),
                ('percentage', models.FloatField()),
                ('Institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.institute')),
            ],
        ),
    ]
